version: '3.8'

services:
  ynab-service:
    build: .
    container_name: ynab-service
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ynab-network

networks:
  ynab-network:
    driver: bridge 